export const images = {
  logo: require('./images/siteLogo.png'),
  instagram: require('./images/instagram.png'),
  linkedin: require('./images/linkedin.png'),
  twitter: require('./images/twitter.png'),
  artwork: require('./images/artwork.png'),
  questionMark: require('./images/questionMark.png'),
  rightThumbsUp: require('./images/rightThumbsUp.png'),
  leftThumbsUp: require('./images/leftThumbsUp.png'),
  virtualAssistent: require('./images/virtualAssistent.png'),
  benText: require('./images/benText.png'),
  lightBulb: require('./images/lightBulb.png'),
  exclamationMan: require('./images/exclamationMan.png'),
  binocularsMan: require('./images/binocularsMan.png'),
  rocket: require('./images/rocket.png'),
  tolq: require('./images/tolq.png'),
  feedbackLabs: require('./images/feedbackLabs.png'),
  codekeeper: require('./images/codekeeper.png'),
  legalSite: require('./images/legalSite.png'),
};
